### ISSUE TITLE
Windows下运行报错

### ISSUE THREAD

**Issue by ykwqdtd** [shing-yu/fanqie-novel-download#48]
<img width="866" alt="屏幕截图 2024-02-17 232546" src="https://github.com/shing-yu/fanqie-novel-download/assets/156038257/4eaf9647-89a6-4c2b-9b0a-1ef1909c0ec8">
求助QAQ
运行环境:
Windows 11 pro 23H2；
python 3.12

**Comment by shing-yu** [comment]
新版本已加入错误提示
看信息应该是这个书不存在或者不能在网页上阅读

**Comment by ykwqdtd** [comment]
我多试了几次，发现有的时候可以有的时候不行，而且书籍id我这边一直不行，换用目录地址有的时候就可以，不知道为什么
