### ISSUE TITLE
建议，ctrl+c在任何时候都返回到开始菜单

### ISSUE THREAD

**Issue by nmweizi** [shing-yu/fanqie-novel-download#50]
在下载或更新状态时，按ctrl+c就直接报错退出了。建议，ctrl+c在任何时候都返回到开始菜单

**Comment by shing-yu** [comment]
按Ctrl+C中断退出应该是所有命令行程序的设计规范
本程序在部分地方使用Ctrl+C触发功能是因为捕获其它快捷键可能需要管理员权限
并不应该滥用Ctrl+C
所以此建议不会被采纳

另外下载状态时并不会直接退出，而是保存被中断前下载的内容
