### ISSUE TITLE
建议，显示重新定义后的默认路径

### ISSUE THREAD

**Issue by nmweizi** [shing-yu/fanqie-novel-download#51]
是否自行选择保存路径(yes/no)(默认:no):
您未选择自定义保存路径，请在获取完成后到默认路径下寻找文件。
(初始默认路径为程序所在文件夹，命令行为执行目录)
** 直接显示路径信息比这个提示更友好 **

**Comment by shing-yu** [comment]
事实上，对于小白用户，显示路径信息可能更不友好，特别是未更改时
其中甚至多数都不知道如何在命令行界面复制内容
并且，需要自定义默认路径的用户在整个用户群体中似乎并不多

如果忘记了路径，可以到 用户文件夹/fanqie_data/config.json 文件内查找
想要重置可以在菜单界面进入选项10
不会采纳此建议
