### ISSUE TITLE
文字显示不全

### ISSUE THREAD

**Issue by myhaooo** [shing-yu/fanqie-novel-download#52]
在epub搜索模式下，出现部分字体无法显示的问题
本机可稳定复现
![screenshot20240308](https://github.com/shing-yu/fanqie-novel-download/assets/67223745/7aa3546a-c36d-43b2-9034-2d22d24c7fa5)

**Comment by wdmmjwxf** [comment]
多次重新搜索后概率恢复正常
![screenshot20240308](https://github.com/shing-yu/fanqie-novel-download/assets/67223745/bfad97d3-c987-4ede-b459-0b1e51437957)

**Comment by shing-yu** [comment]
搜索模式代码并不是独立的
所有模式都是一个代码
怀疑与近期番茄频繁返回空内容有关系

**Comment by wdmmjwxf** [comment]
是的，在下载章节时也会有时出现返回空json的报错
